-- Drafts generated by Meridian in the user's writing voice, awaiting review.
-- Run once: psql -U your_user -d meridian -f backend/db/migrations/006_drafts.sql

CREATE TABLE IF NOT EXISTS drafts (
    id SERIAL PRIMARY KEY,
    account_id INTEGER REFERENCES gmail_accounts(id),
    to_email VARCHAR(255),
    subject TEXT,
    body TEXT,
    thread_email_id INTEGER REFERENCES emails(id),
    status VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'sent', 'discarded'
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_drafts_status ON drafts(status);
